name: graphql_example
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  graphql_flutter: ^5.1.2
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  intl: ^0.19.0
  hive: ^2.2.3
  injectable: ^2.4.4
  fluttertoast: ^8.2.5
  json_annotation: ^4.9.0
  connectivity_plus: ^6.0.5
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  dio: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true
